SECRET_KEY = "YOUR SECRET KEY";
PORT = "YOUR PORT";
NODE_ENV = "development";
WEATHER_API_KEY = "YOUR WEATHER API KEY";
GOOGLE_CLIENT_ID = "YOUR GOOGLE CLIENT ID";
GOOGLE_SECRET_ID = "YOUR GOOGLE SECRET ID";
